global using System;
global using System.ComponentModel;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.Globalization;
global using System.IO;
global using System.Linq;
global using System.Runtime.CompilerServices;
global using System.Text;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Controls;
global using RIS;
global using RIS.Extensions;
global using RIS.Collections;
global using RIS.Collections.Chunked;
global using RIS.Collections.Extensions;
global using RIS.Collections.Nestable;
global using RIS.Randomizing;
global using RIS.Synchronization;
global using RIS.Localization;
global using RIS.Localization.Providers;
global using RIS.Logging;
global using RIS.Mathematics;
global using RIS.Unions;
global using RIS.Unions.Types;
global using Memenim.Framework.Flyouts;
global using Memenim.Framework.Generating;
global using Memenim.Framework.Generic;
global using Memenim.Framework.Navigation;
global using Memenim.Framework.Pages;
global using Memenim.Framework.Pages.ViewModel;
global using Memenim.Framework.Protocols;
global using Memenim.Framework.Protocols.Schemas;
global using Memenim.Framework.Settings;
global using Memenim.Framework.Utils;
global using Memenim.Framework.Widgets;
global using MahApps.Metro.Controls;

global using DialogManager = Memenim.Framework.Dialogs.DialogManager;
global using Environment = RIS.Environment;
global using LogManager = RIS.Logging.LogManager;
global using LocalizationManager = RIS.Localization.LocalizationManager;
global using Math = RIS.Mathematics.Math;
global using ProtocolManager = Memenim.Framework.Protocols.ProtocolManager;
global using SettingsManager = Memenim.Framework.Settings.SettingsManager;
global using SysEnvironment = System.Environment;
global using SysMath = System.Math;
